#!/bin/bash

echo "🎛️ Setting up Rosita AUv3 Extension"
echo "==================================="

echo ""
echo "MANUAL STEPS IN XCODE:"
echo ""
echo "1. Open Rosita.xcodeproj in Xcode"
echo ""
echo "2. Add New Target:"
echo "   • File → New → Target"
echo "   • iOS → Application Extension → Audio Unit Extension"
echo "   • Product Name: RositaAUv3"
echo "   • Language: Swift"
echo "   • Project: Rosita"
echo "   • Embed in Application: Rosita"
echo "   • ✅ Include UI"
echo ""
echo "3. Replace Generated Files:"
echo "   • Delete the generated files in RositaAUv3 group"
echo "   • Add the files from RositaAUv3/ folder:"
echo "     - RositaAudioUnit.swift"
echo "     - RositaAudioUnitViewController.swift"
echo "     - Info.plist (already created)"
echo ""
echo "4. Configure Bundle ID:"
echo "   • Select RositaAUv3 target"
echo "   • General tab → Identity"
echo "   • Bundle Identifier: com.jadewii.rosita.RositaAUv3"
echo ""
echo "5. Configure Audio Component:"
echo "   • Already configured in Info.plist"
echo "   • Type: aumu (Music Device)"
echo "   • Subtype: rsit (unique to Rosita)"
echo ""
echo "6. Share Code Between Targets:"
echo "   • Select AudioEngine.swift"
echo "   • File inspector → Target Membership"
echo "   • ✅ Check both Rosita and RositaAUv3"
echo ""
echo "7. Build & Test:"
echo "   • Select RositaAUv3 scheme"
echo "   • Build and run on device (not simulator)"
echo "   • Open GarageBand → Add Instrument → Audio Unit"
echo "   • Find 'Wiistrument: Rosita'"
echo ""
echo "✅ Your AUv3 files are ready in RositaAUv3/ folder!"
echo ""
echo "Benefits:"
echo "• Works in GarageBand, Logic Pro, Cubasis, AUM"
echo "• Professional plugin format"
echo "• Multiple instances support"
echo "• Parameter automation"
echo "• MIDI support"